### ISSUE TITLE
Bikeshed: fromAsync vs. asyncFrom

### ISSUE THREAD

**Issue by domenic** [js-choi/proposal-array-async-from#2]
We have a weak precedent that when there are methods with both sync and async versions, async is a _suffix_, not a prefix.

`Atomics.waitAsync()` is the ES precedent. Web GPU has a number of others.

**Comment by js-choi** [comment]
This is a good point. I will change the proposal’s method name to `Array.fromAsync` sometime before the August meeting.￼

**Comment by ljharb** [comment]
I was happy with `asyncFrom`, but I can easily convince myself that `Array.fromAsync` makes more sense because it's "an array from an async iterator" rather than "it's asynchronously an array from something".
